version: '3'

services:
  static-file-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./public:/app/public
    environment:
      - PORT=3000
    restart: unless-stopped 